### ISSUE TITLE
Неправильно вставился текст описания здания

### ISSUE THREAD

**Issue by Eeenkeeei** [Kostya-228/Eminem#4]
Скопировался не до конца:

![image](https://user-images.githubusercontent.com/30475602/80311618-5b78e200-87e9-11ea-9f44-11c72a7ee5c7.png)

**Comment by intsynko** [comment]
Выложил в [PrePrePre Alfa #2](https://github.com/Kostya-228/Eminem/releases/tag/0.1.1) update, чекни, пофиксилось ли

**Comment by intsynko** [comment]
Проблема решена [коммитом](https://github.com/Kostya-228/Eminem/commit/d28e35648f550f021c38cc58b681e5911737328d)
