### ISSUE TITLE
Ошибка при заполнении файла MS Word

### ISSUE THREAD

**Issue by Kba05** [Kostya-228/Eminem#6]
В файл MS word не полностью добавляются  заданные этажи, при подсчете длины кабеля .

Задал  9 этажей ,а получил 5. Предоставляю скрин результата 

![Снимок](https://user-images.githubusercontent.com/59648721/80317538-2088a580-880d-11ea-8587-df0a0f9fbf45.JPG)

**Comment by intsynko** [comment]
Нужен скрин, так не понятно где именно

**Comment by intsynko** [comment]
Проблема решена [коммитом](https://github.com/Kostya-228/Eminem/commit/d28e35648f550f021c38cc58b681e5911737328d)
